language: python
python:
  - "3.8"
env:
  global:
    DEPLOY=false
    VERSION_TYPE=patch
before_install:
- pip install poetry
install:
- poetry install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - poetry run coverage run -m pytest
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_deploy:
- poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    branch: master
