language: python
python:
  - "3.8"
env:
  global:
    DEPLOY=false
    VERSION_TYPE=patch
before_install:
- pip install poetry
install:
- poetry install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - poetry run coverage run -m pytest
  - |
    if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
      poetry version $VERSION_TYPE
      poetry build
      poetry publish
      sh .travis-push.sh
    fi
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
